language: perl
perl:
  - 5.8
  - "5.10"  # Without quotes this will use perl version 5.1
  - 5.12
  - 5.14
  - 5.16
  - 5.18

before_script:
    - psql -c 'create database nessy;' -U postgres
    - git clone --depth 1 https://github.com/genome/nessy-server.git
    - pushd nessy-server
    - git --no-pager show -s
    - sudo pip install -r requirements.txt
    - LOCKING_DB='postgres://postgres@localhost/nessy' ./devserver &
    - popd

script:
    - NESSY_SERVER_URL=http://localhost:5000 prove -I t/lib --lib --verbose --recurse t/
